<a href="https://colab.research.google.com/github/123Rajani/Implementing-AND-OR-XOR-Gates/blob/main/Programming_a_neuron_IM_2019_052_IM_2019_107.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

You are supposed to write a program to implement a single neuron-based machine learning system. Use the ADALINE architecture and its weight update formula to make your system. Train the system with input-output pairs of AND, OR and XOR gates and observe the outputs.

IM/2019/107-Rajani Navoda
IM/2019/052-Tharindu Adhikari

In [ ]:
#### LEARNING AND GATE

# import Python Libraries

import numpy as np
from matplotlib import pyplot as plt

 
# definition of the sigmoidFunction Function
def sigmoidFunction(z):
    return 1 / (1 + np.exp(-z))
 
# Initialization of the neural network parameters.
# constraints: weight range 0-1. 
# bies values =0.

def NNparameters(input, HLnurons, output):
    weight1 = np.random.randn(HLnurons, input)
    weight2 = np.random.randn(output, HLnurons)
    b1 = np.zeros((HLnurons, 1))
    b2 = np.zeros((output, 1))
     
    parameters = {"weight1" : weight1, "b1": b1,
                  "weight2" : weight2, "b2": b2}
    return parameters


# Forward Propagation
def forwardPropagation(X, Y, parameters):
    m = X.shape[1]
    weight1 = parameters["weight1"]
    weight2 = parameters["weight2"]
    b1 = parameters["b1"]
    b2 = parameters["b2"]
 
    Z1 = np.dot(weight1, X) + b1
    A1 = sigmoidFunction(Z1)
    Z2 = np.dot(weight2, A1) + b2
    A2 = sigmoidFunction(Z2)
 
    cache = (Z1, A1, weight1, b1, Z2, A2, weight2, b2)
    logprobs = np.multiply(np.log(A2), Y) + np.multiply(np.log(1 - A2), (1 - Y))
    cost = -np.sum(logprobs) / m
    return cost, cache, A2
 


# Backward Propagation
def backwardPropagation(X, Y, cache):
    m = X.shape[1]
    (Z1, A1, weight1, b1, Z2, A2, weight2, b2) = cache
     
    dZ2 = A2 - Y
    dweight2 = np.dot(dZ2, A1.T) / m
    db2 = np.sum(dZ2, axis = 1, keepdims = True)
     
    dA1 = np.dot(weight2.T, dZ2)
    dZ1 = np.multiply(dA1, A1 * (1- A1))
    dweight1 = np.dot(dZ1, X.T) / m
    db1 = np.sum(dZ1, axis = 1, keepdims = True) / m
     
    gradients = {"dZ2": dZ2, "dweight2": dweight2, "db2": db2,
                 "dZ1": dZ1, "dweight1": dweight1, "db1": db1}
    return gradients
 

# Updating the weights based on the negative gradients
def updateParameters(parameters, gradients, learningRate):
    parameters["weight1"] = parameters["weight1"] - learningRate * gradients["dweight1"]
    parameters["weight2"] = parameters["weight2"] - learningRate * gradients["dweight2"]
    parameters["b1"] = parameters["b1"] - learningRate * gradients["db1"]
    parameters["b2"] = parameters["b2"] - learningRate * gradients["db2"]
    return parameters
 

# Model to learn the AND truth table


X = np.array([[0, 0, 1, 1], [0, 1, 0, 1]]) #AND inputs
Y = np.array([[0, 0, 0, 1]]) # AND output
 
# Define model parameters
HLnurons = 4 # number of hidden layer neurons (2)
input = X.shape[0] # number of input features (2)
output = Y.shape[0] # number of output features (1)
parameters = NNparameters(input, HLnurons, output)
epoch = 100000  ##number of learning cycles
learningRate = 0.01
losses = np.zeros((epoch, 1)) 
 
for i in range(epoch):
    losses[i, 0], cache, A2 = forwardPropagation(X, Y, parameters)
    gradients = backwardPropagation(X, Y, cache)
    parameters = updateParameters(parameters, gradients, learningRate)
 
# Testing1
X = np.array([[1, 0, 0, 1], [0, 1, 0, 1]]) # AND input
cost, _, A2 = forwardPropagation(X, Y, parameters)
prediction = (A2 > 0.5) * 1.0
# print(A2)
print(prediction)

[[0. 0. 0. 1.]]


In [ ]:
#### LEARNING OR GATE

# import Python Libraries

import numpy as np
from matplotlib import pyplot as plt

 
# definition of the sigmoidFunction Function
def sigmoidFunction(z):
    return 1 / (1 + np.exp(-z))
 
# Initialization of the neural network parameters.
# constraints: weight range 0-1. 
# bies values =0.

def NNparameters(input, HLnurons, output):
    weight1 = np.random.randn(HLnurons, input)
    weight2 = np.random.randn(output, HLnurons)
    b1 = np.zeros((HLnurons, 1))
    b2 = np.zeros((output, 1))
     
    parameters = {"weight1" : weight1, "b1": b1,
                  "weight2" : weight2, "b2": b2}
    return parameters


# Forward Propagation
def forwardPropagation(X, Y, parameters):
    m = X.shape[1]
    weight1 = parameters["weight1"]
    weight2 = parameters["weight2"]
    b1 = parameters["b1"]
    b2 = parameters["b2"]
 
    Z1 = np.dot(weight1, X) + b1
    A1 = sigmoidFunction(Z1)
    Z2 = np.dot(weight2, A1) + b2
    A2 = sigmoidFunction(Z2)
 
    cache = (Z1, A1, weight1, b1, Z2, A2, weight2, b2)
    logprobs = np.multiply(np.log(A2), Y) + np.multiply(np.log(1 - A2), (1 - Y))
    cost = -np.sum(logprobs) / m
    return cost, cache, A2
 


# Backward Propagation
def backwardPropagation(X, Y, cache):
    m = X.shape[1]
    (Z1, A1, weight1, b1, Z2, A2, weight2, b2) = cache
     
    dZ2 = A2 - Y
    dweight2 = np.dot(dZ2, A1.T) / m
    db2 = np.sum(dZ2, axis = 1, keepdims = True)
     
    dA1 = np.dot(weight2.T, dZ2)
    dZ1 = np.multiply(dA1, A1 * (1- A1))
    dweight1 = np.dot(dZ1, X.T) / m
    db1 = np.sum(dZ1, axis = 1, keepdims = True) / m
     
    gradients = {"dZ2": dZ2, "dweight2": dweight2, "db2": db2,
                 "dZ1": dZ1, "dweight1": dweight1, "db1": db1}
    return gradients
 

# Updating the weights based on the negative gradients
def updateParameters(parameters, gradients, learningRate):
    parameters["weight1"] = parameters["weight1"] - learningRate * gradients["dweight1"]
    parameters["weight2"] = parameters["weight2"] - learningRate * gradients["dweight2"]
    parameters["b1"] = parameters["b1"] - learningRate * gradients["db1"]
    parameters["b2"] = parameters["b2"] - learningRate * gradients["db2"]
    return parameters
 

# Model to learn the OR truth table

X = np.array([[0, 0, 1, 1], [0, 1, 0, 1]]) # OR inputs
Y = np.array([[0, 1, 1, 1]]) # OR output
 
# Define model parameters
HLnurons = 4 # number of hidden layer neurons (2)
input = X.shape[0] # number of input features (2)
output = Y.shape[0] # number of output features (1)
parameters = NNparameters(input, HLnurons, output)
epoch = 100000  ##number of learning cycles
learningRate = 0.01
losses = np.zeros((epoch, 1)) 
 
for i in range(epoch):
    losses[i, 0], cache, A2 = forwardPropagation(X, Y, parameters)
    gradients = backwardPropagation(X, Y, cache)
    parameters = updateParameters(parameters, gradients, learningRate)
 

# Testing2
X = np.array([[1, 0, 0, 1], [0, 1, 0, 1]]) # OR input
cost, _, A2 = forwardPropagation(X, Y, parameters)
prediction = (A2 > 0.5) * 1.0
# print(A2)
print(prediction)

[[1. 1. 0. 1.]]


In [ ]:
#### LEARNING XOR GATE

# import Python Libraries

import numpy as np
from matplotlib import pyplot as plt

 
# definition of the sigmoidFunction Function
def sigmoidFunction(z):
    return 1 / (1 + np.exp(-z))
 
# Initialization of the neural network parameters.
# constraints: weight range 0-1. 
# bies values =0.

def NNparameters(input, HLnurons, output):
    weight1 = np.random.randn(HLnurons, input)
    weight2 = np.random.randn(output, HLnurons)
    b1 = np.zeros((HLnurons, 1))
    b2 = np.zeros((output, 1))
     
    parameters = {"weight1" : weight1, "b1": b1,
                  "weight2" : weight2, "b2": b2}
    return parameters


# Forward Propagation
def forwardPropagation(X, Y, parameters):
    m = X.shape[1]
    weight1 = parameters["weight1"]
    weight2 = parameters["weight2"]
    b1 = parameters["b1"]
    b2 = parameters["b2"]
 
    Z1 = np.dot(weight1, X) + b1
    A1 = sigmoidFunction(Z1)
    Z2 = np.dot(weight2, A1) + b2
    A2 = sigmoidFunction(Z2)
 
    cache = (Z1, A1, weight1, b1, Z2, A2, weight2, b2)
    logprobs = np.multiply(np.log(A2), Y) + np.multiply(np.log(1 - A2), (1 - Y))
    cost = -np.sum(logprobs) / m
    return cost, cache, A2
 


# Backward Propagation
def backwardPropagation(X, Y, cache):
    m = X.shape[1]
    (Z1, A1, weight1, b1, Z2, A2, weight2, b2) = cache
     
    dZ2 = A2 - Y
    dweight2 = np.dot(dZ2, A1.T) / m
    db2 = np.sum(dZ2, axis = 1, keepdims = True)
     
    dA1 = np.dot(weight2.T, dZ2)
    dZ1 = np.multiply(dA1, A1 * (1- A1))
    dweight1 = np.dot(dZ1, X.T) / m
    db1 = np.sum(dZ1, axis = 1, keepdims = True) / m
     
    gradients = {"dZ2": dZ2, "dweight2": dweight2, "db2": db2,
                 "dZ1": dZ1, "dweight1": dweight1, "db1": db1}
    return gradients
 

# Updating the weights based on the negative gradients
def updateParameters(parameters, gradients, learningRate):
    parameters["weight1"] = parameters["weight1"] - learningRate * gradients["dweight1"]
    parameters["weight2"] = parameters["weight2"] - learningRate * gradients["dweight2"]
    parameters["b1"] = parameters["b1"] - learningRate * gradients["db1"]
    parameters["b2"] = parameters["b2"] - learningRate * gradients["db2"]
    return parameters
 

# Model to learn the OR truth table

X = np.array([[0, 0, 1, 1], [0, 1, 0, 1]]) # XOR inputs
Y = np.array([[0, 1, 1, 0]]) # XOR output
 
# Define model parameters
HLnurons = 4 # number of hidden layer neurons (2)
input = X.shape[0] # number of input features (2)
output = Y.shape[0] # number of output features (1)
parameters = NNparameters(input, HLnurons, output)
epoch = 100000  ##number of learning cycles
learningRate = 0.01
losses = np.zeros((epoch, 1)) 
 
for i in range(epoch):
    losses[i, 0], cache, A2 = forwardPropagation(X, Y, parameters)
    gradients = backwardPropagation(X, Y, cache)
    parameters = updateParameters(parameters, gradients, learningRate)
 

# Testing3
X = np.array([[1, 0, 0, 1], [0, 1, 0, 1]]) # XOR input
cost, _, A2 = forwardPropagation(X, Y, parameters)
prediction = (A2 > 0.5) * 1.0
# print(A2)
print(prediction)

[[1. 1. 0. 0.]]
